### ISSUE TITLE
image feature to embedding vector

### ISSUE THREAD

**Issue by MaLo94** [chunmeifeng/SPRC#2]
Greetings
Thanks for the great work on the proposed model in advance. I've been exploring the image encoder module and noticed it produces a 2D array (32*256) as the image feature output. I'm interested in discussing the possibility of having a 1D array output, potentially achieved by adding a simple MLP layer. Is there any idea that help me?

**Comment by baiyang4** [comment]
Thanks for your interest, 
the 32*256 output is derived by 32 learnable queries (see Blip-2 paper in detail). To make the output into 1 vector rather than 32 (I suggest not change the pre-trained weigths of Blip-2), you can either 
1. average the 32 learable queries into 1, and use this 1 query do the cross-attenion;
2. average the output 32*256 array (you can average and add a MLP, or use a new learable query to perform cross attention with the 32*256 output).  
Please let me know if you have questions with the above suggestions.

**Comment by hmd78** [comment]
So you mean that the model should be finetuned from scratch with 1 query token instead of 32 query tokens?
and to assure that i understood what you suggested, in the second method , during training, the output of learning queries (32 * 256) can be averaged or pass through a MLP or add another learnable query token with those 32 query tokens and it should be trained with cross-attention (no self-attention with those 32 queries)?

And don't you think that with these method there would be a noticeable performance drop?
(Maybe many fine-grained attributes features get lost)

**Comment by baiyang4** [comment]
> So you mean that the model should be finetuned from scratch with 1 query token instead of 32 query tokens? and to assure that i understood what you suggested, in the second method , during training, the output of learning queries (32 * 256) can be averaged or pass through a MLP or add another learnable query token with those 32 query tokens and it should be trained with cross-attention (no self-attention with those 32 queries)?
> 
> And don't you think that with these method there would be a noticeable performance drop? (Maybe many fine-grained attributes features get lost)

1. I think use 1 query token (from pretrained BLIP-2) to train a CIR model is a possible way to achieve 1 vector ouput. I think the performance might drop in this way.
2. In the BLIP-2 model, 32 learnable queries are employed for cross-attention with image embeddings. What I suggest is to   use an additional learnable query for cross-attention with the output (32 * D). This new query would aim to produce a 1 * D vector. I believe that this modification has the potential to improve performance.

**Comment by hmd78** [comment]
Thank you for your helpful answer.

Could you guide me where are the modification to be made for second method you said?

**Comment by baiyang4** [comment]
> Thank you for your helpful answer.
> 
> Could you guide me where are the modification to be made for second method you said?

you can modify the forward function at SPRC/src/lavis/models/blip2_models/blip2_qformer_cir_align_prompt.py

**Comment by hmd78** [comment]
I think i should change qformer.py file. Because query tokens and cross attention layers are used there.
Am I right?
